[project]
name = "bookmark-processor"
version = "0.1.0"
description = "A parallelized pipeline to process bookmarks."
requires-python = ">=3.10"
dependencies = [
    # keep-sorted start
    "prefect>=2.0",
    "httpx",
    "playwright",
    "pydantic",
    "beautifulsoup4",
    "lxml",
    "llm",
    "llm-mlx",
    "typer",
    "pendulum",
    # keep-sorted end
]

[project.optional-dependencies]
dev = [
    "pytest",
    "respx",
    "pytest-mock",
    "ruff",
]

[project.scripts]
bookmark-processor = "bookmark_processor.main:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "--cov=bookmark_processor --cov-report=term-missing"
pythonpath = ["src"] # Add src to python path for tests to find the package

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
